AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layers (stage-aware)

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage name used for resource naming.

Resources:
  OtlpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub '${Stage}-chase-light-otlp-layer'
      ContentUri: ./otlp
      CompatibleRuntimes: [nodejs22.x]
    Metadata:
      BuildMethod: makefile

Outputs:
  Stage:
    Value: !Ref Stage

  OtlpLayerVersionArn:
    Value: !Ref OtlpLayer

  OtlpLayerName:
    Value: !Sub 'otlp-layer-${Stage}'
