version: 2
updates:
  # GitHub Actions の依存関係監視
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    reviewers:
      - "tri-star"
    commit-message:
      prefix: "feat"
      include: "scope"

  # ルートフォルダの npm 依存関係監視
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "root"
    reviewers:
      - "tri-star"
    commit-message:
      prefix: "feat"
      include: "scope"

  # Backend パッケージの依存関係監視
  - package-ecosystem: "npm"
    directory: "/packages/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    reviewers:
      - "tri-star"
    commit-message:
      prefix: "feat"
      include: "scope"

  # Frontend パッケージの依存関係監視
  - package-ecosystem: "npm"
    directory: "/packages/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "tri-star"
    commit-message:
      prefix: "feat"
      include: "scope"

  # Shared パッケージの依存関係監視
  - package-ecosystem: "npm"
    directory: "/packages/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "18:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "shared"
    reviewers:
      - "tri-star"
    commit-message:
      prefix: "feat"
      include: "scope"