version: '3'

services:
  workspace:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        TZ: Asia/Tokyo
    volumes:
      - ./:/workspace
    working_dir: /workspace
    tty: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
      - test_db
    # networks:
    #   - app-network

  db:
    image: public.ecr.aws/docker/library/postgres:15.6-bookworm # Supabaseと合わせる
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '15432:5432'

  test_db:
    image: public.ecr.aws/docker/library/postgres:15.6-bookworm
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - '15433:15432'

volumes:
  db_data:
  test_db_data:
# networks:
#   app-network:
#     driver: bridge
