services:
  db:
    image: public.ecr.aws/docker/library/postgres:15.6-bookworm # Supabaseと合わせる
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  test_db:
    image: public.ecr.aws/docker/library/postgres:15.6-bookworm
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: test_db
    volumes:
      - test_db_data:/var/lib/postgresql/data
    ports:
      - '10000:5432'

volumes:
  db_data:
  test_db_data:
