# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "chase-light-local-api-stack"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=local"

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

# Development environment
[dev]
[dev.global.parameters]
stack_name = "chase-light-dev-api-stack"

[dev.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=dev"
region = "ap-northeast-1"

# Staging environment
[staging]
[staging.global.parameters]
stack_name = "chase-light-staging-api-stack"

[staging.build.parameters]
cached = true
parallel = true

[staging.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=staging"
region = "ap-northeast-1"

# Production environment
[prod]
[prod.global.parameters]
stack_name = "chase-light-prod-api-stack"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
parameter_overrides = "Stage=prod"
region = "ap-northeast-1"
