version = 0.1
[default]
[default.local_start_api]
[default.local_start_api.parameters]
warm_containers = "EAGER"
env_vars = "env.json"

[default.local_invoke]
[default.local_invoke.parameters]
env_vars = "env.json"
