AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Chase Light Backend Infrastructure'

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs22.x
    Environment:
      Variables:
        USE_AWS: !Ref UseAws
        STAGE: !Ref Stage
        APP_STAGE: !Ref Stage
        DB_HOST: ""
        DB_PORT: ""
        DB_USER: ""
        DB_PASSWORD: ""
        DB_NAME: ""
        DB_SSL: "false"
        OPENAI_API_KEY: ""

Parameters:
  UseAws:
    Type: String
    Default: 'true'
    Description: Flag to indicate if running in AWS environment
  Stage:
    Type: String
    Default: 'dev'
    Description: Stage environment (dev, staging, prod)

Resources:
  # SQS Queues
  ProcessUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-process-updates-queue"
      VisibilityTimeout: 360
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessUpdatesDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessUpdatesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-process-updates-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  # Translation Jobs Queue
  TranslationJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-translation-jobs-queue"
      VisibilityTimeout: 360
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TranslationJobsDeadLetterQueue.Arn
        maxReceiveCount: 3

  TranslationJobsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-translation-jobs-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  # Lambda Functions
  ListDetectTargetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-list-detect-targets"
      CodeUri: ../dist/lambda/list-detect-targets/
      Handler: index.handler
      Description: 'List detect targets for monitoring'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-list-detect-targets*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"

  DetectDataSourceUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-detect-datasource-updates"
      CodeUri: ../dist/lambda/detect-datasource-updates/
      Handler: index.handler
      Description: 'Detect updates for a data source'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-detect-datasource-updates*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"

  ProcessUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-process-updates"
      CodeUri: ../dist/lambda/process-updates/
      Handler: index.handler
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessUpdatesQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/openai/api_key"
        - Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ProcessUpdatesQueue.Arn

  TranslateActivityBodyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-translate-activity-body"
      CodeUri: ../dist/lambda/translate-activity-body/
      Handler: index.handler
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TranslationJobsQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/openai/api_key"
        - Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt TranslationJobsQueue.Arn

  GenerateDigestNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-generate-digest-notifications"
      CodeUri: ../dist/lambda/generate-digest-notifications/
      Handler: index.handler
      Description: 'Generate digest notifications for subscribed users'
      Timeout: 120
      Environment:
        Variables:
          DIGEST_DEFAULT_LIMIT: "200"
      Events:
        GenerateDigestNotificationsSchedule:
          Type: Schedule
          Properties:
            Name: !Sub "${AWS::StackName}-generate-digest-notifications-schedule"
            Description: "Run digest notification generation every 30 minutes"
            Schedule: "cron(0/30 * * * ? *)"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-generate-digest-notifications*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource:
                - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"

  # Step Functions State Machine
  DataSourceUpdateDetectionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-data-source-update-detection"
      DefinitionUri: data-source-update-detection.asl.json
      DefinitionSubstitutions:
        ListDetectTargetsFunctionArn: !GetAtt ListDetectTargetsFunction.Arn
        DetectDataSourceUpdatesFunctionArn: !GetAtt DetectDataSourceUpdatesFunction.Arn
        ProcessUpdatesFunction: !GetAtt ProcessUpdatesFunction.Arn
        ProcessUpdatesQueueUrl: !Ref ProcessUpdatesQueue
        DataSourceUpdateDetectionLogGroup.Arn: !GetAtt DataSourceUpdateDetectionLogGroup.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DataSourceUpdateDetectionLogGroup.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt ListDetectTargetsFunction.Arn
                - !GetAtt DetectDataSourceUpdatesFunction.Arn
                - !GetAtt ProcessUpdatesFunction.Arn
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProcessUpdatesQueue.Arn
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogStreams
              Resource: 
                - !GetAtt DataSourceUpdateDetectionLogGroup.Arn
                - !Sub "${DataSourceUpdateDetectionLogGroup.Arn}:*"

  # CloudWatch Log Group for Step Functions
  DataSourceUpdateDetectionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/stepfunctions/${AWS::StackName}-data-source-update-detection"
      RetentionInDays: 30

  # EventBridge Rule for daily execution
  DataSourceUpdateDetectionScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${AWS::StackName}-data-source-update-detection-schedule"
      Description: "Daily execution of data source update detection workflow"
      ScheduleExpression: "cron(0 8 * * ? *)"  # Daily at 17:00 JST (08:00 UTC)
      State: ENABLED
      Targets:
        - Arn: !Ref DataSourceUpdateDetectionStateMachine
          Id: "DataSourceUpdateDetectionTarget"
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn

  # IAM Role for EventBridge to execute Step Functions
  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref DataSourceUpdateDetectionStateMachine

  # SNS Topic for alerts
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"
      DisplayName: "Data source update detection alerts"

  # CloudWatch Alarms
  StepFunctionsExecutionFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-stepfunctions-execution-failed"
      AlarmDescription: "Alert when Step Functions execution fails"
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DataSourceUpdateDetectionStateMachineArn
          Value: !Ref DataSourceUpdateDetectionStateMachine
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-lambda-errors"
      AlarmDescription: "Alert when Lambda functions have errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProcessUpdatesFunction
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  ProcessUpdatesDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-dlq-messages"
      AlarmDescription: "Alert when messages appear in DLQ"
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ProcessUpdatesDeadLetterQueue.QueueName
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  TranslationJobsDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-translation-dlq-messages"
      AlarmDescription: "Alert when messages appear in Translation Jobs DLQ"
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TranslationJobsDeadLetterQueue.QueueName
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

Outputs:
  DataSourceUpdateDetectionStateMachineArn:
    Description: 'ARN of the data source update detection state machine'
    Value: !Ref DataSourceUpdateDetectionStateMachine
    Export:
      Name: !Sub "${AWS::StackName}-DataSourceUpdateDetectionStateMachineArn"
  
  ListDetectTargetsFunctionArn:
    Description: 'ARN of the list detect targets function'
    Value: !GetAtt ListDetectTargetsFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ListDetectTargetsFunctionArn"

  DetectDataSourceUpdatesFunctionArn:
    Description: 'ARN of the detect data source updates function'
    Value: !GetAtt DetectDataSourceUpdatesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DetectDataSourceUpdatesFunctionArn"

  ProcessUpdatesFunctionArn:
    Description: 'ARN of the process updates function'
    Value: !GetAtt ProcessUpdatesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesFunctionArn"

  ProcessUpdatesQueueUrl:
    Description: 'URL of the process updates SQS queue'
    Value: !Ref ProcessUpdatesQueue
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesQueueUrl"

  ProcessUpdatesQueueArn:
    Description: 'ARN of the process updates SQS queue'
    Value: !GetAtt ProcessUpdatesQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesQueueArn"

  ScheduleRuleArn:
    Description: 'ARN of the EventBridge schedule rule'
    Value: !GetAtt DataSourceUpdateDetectionScheduleRule.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ScheduleRuleArn"

  AlertsTopicArn:
    Description: 'ARN of the SNS alerts topic'
    Value: !Ref AlertsTopic
    Export:
      Name: !Sub "${AWS::StackName}-AlertsTopicArn"

  TranslateActivityBodyFunctionArn:
    Description: 'ARN of the translate activity body function'
    Value: !GetAtt TranslateActivityBodyFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TranslateActivityBodyFunctionArn"

  TranslationJobsQueueUrl:
    Description: 'URL of the translation jobs SQS queue'
    Value: !Ref TranslationJobsQueue
    Export:
      Name: !Sub "${AWS::StackName}-TranslationJobsQueueUrl"

  TranslationJobsQueueArn:
    Description: 'ARN of the translation jobs SQS queue'
    Value: !GetAtt TranslationJobsQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-TranslationJobsQueueArn"
