AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Repository monitoring workflow with Step Functions'

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs22.x
    Environment:
      Variables:
        USE_AWS: !Ref UseAws
        STAGE: !Ref Stage
        APP_STAGE: !Ref Stage
        DB_HOST: ""
        DB_PORT: ""
        DB_USER: ""
        DB_PASSWORD: ""
        DB_NAME: ""
        DB_SSL: "false"
        OPENAI_API_KEY: ""

Parameters:
  UseAws:
    Type: String
    Default: 'true'
    Description: Flag to indicate if running in AWS environment
  Stage:
    Type: String
    Default: 'dev'
    Description: Stage environment (dev, staging, prod)

Resources:
  # SQS Queues
  ProcessUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-process-updates-queue"
      VisibilityTimeoutSeconds: 360
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessUpdatesDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessUpdatesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${AWS::StackName}-process-updates-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  # Lambda Functions
  ListDataSourcesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-list-datasources"
      CodeUri: ../dist/lambda/list-datasources/
      Handler: index.handler
      Description: 'List data sources for monitoring'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-list-datasources*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"

  DetectDataSourceUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-detect-datasource-updates"
      CodeUri: ../dist/lambda/detect-datasource-updates/
      Handler: index.handler
      Description: 'Detect updates for a data source'
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-detect-datasource-updates*"
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"

  ProcessUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-process-updates"
      CodeUri: ../dist/lambda/process-updates/
      Handler: index.handler
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessUpdatesQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource: 
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/supabase/db_url"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}/openai/api_key"
        - Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ProcessUpdatesQueue.Arn

  # Step Functions State Machine
  RepositoryMonitoringStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${AWS::StackName}-repository-monitoring"
      DefinitionUri: repository-monitoring.asl.json
      DefinitionSubstitutions:
        ListDataSourcesFunctionArn: !GetAtt ListDataSourcesFunction.Arn
        DetectDataSourceUpdatesFunctionArn: !GetAtt DetectDataSourceUpdatesFunction.Arn
        ProcessUpdatesFunction: !GetAtt ProcessUpdatesFunction.Arn
        ProcessUpdatesQueueUrl: !Ref ProcessUpdatesQueue
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt ListDataSourcesFunction.Arn
                - !GetAtt DetectDataSourceUpdatesFunction.Arn
                - !GetAtt ProcessUpdatesFunction.Arn
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProcessUpdatesQueue.Arn
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/stepfunctions/${AWS::StackName}-repository-monitoring*"

  # CloudWatch Log Group for Step Functions
  RepositoryMonitoringLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/stepfunctions/${AWS::StackName}-repository-monitoring"
      RetentionInDays: 30

Outputs:
  StateMachineArn:
    Description: 'ARN of the repository monitoring state machine'
    Value: !Ref RepositoryMonitoringStateMachine
    Export:
      Name: !Sub "${AWS::StackName}-StateMachineArn"
  
  ListDataSourcesFunctionArn:
    Description: 'ARN of the list data sources function'
    Value: !GetAtt ListDataSourcesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ListDataSourcesFunctionArn"

  DetectDataSourceUpdatesFunctionArn:
    Description: 'ARN of the detect data source updates function'
    Value: !GetAtt DetectDataSourceUpdatesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-DetectDataSourceUpdatesFunctionArn"

  ProcessUpdatesFunctionArn:
    Description: 'ARN of the process updates function'
    Value: !GetAtt ProcessUpdatesFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesFunctionArn"

  ProcessUpdatesQueueUrl:
    Description: 'URL of the process updates SQS queue'
    Value: !Ref ProcessUpdatesQueue
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesQueueUrl"

  ProcessUpdatesQueueArn:
    Description: 'ARN of the process updates SQS queue'
    Value: !GetAtt ProcessUpdatesQueue.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ProcessUpdatesQueueArn"