AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Chase Light Backend Infrastructure'

Globals:
  Function:
    Timeout: 60
    Runtime: nodejs22.x
    Layers:
      - !If [UseParamsSecretsExtension, arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:21, !Ref AWS::NoValue]
      - !If [UseParamsSecretsExtension, !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:otel-collector:7', !Ref AWS::NoValue]
      - !If [UseParamsSecretsExtension, !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:${Stage}-chase-light-otlp-layer:${OtlpLayerVersion}', !Ref AWS::NoValue]
    Environment:
      Variables:
        USE_AWS: !Ref UseAws
        STAGE: !Ref Stage
        APP_STAGE: !Ref Stage
        FRONTEND_URL: !Ref FrontendUrl
        DB_HOST: ""
        DB_PORT: ""
        DB_USER: ""
        DB_PASSWORD: ""
        DB_NAME: ""
        DB_SSL: !Ref UseAws
        OPENAI_API_KEY: ""
        NODE_OPTIONS: !Join
          - " "
          - !If [UseParamsSecretsExtension, "--import=/opt/nodejs/otel-setup.mjs", ""]
          - !If [IsProd, "", "--enable-source-maps"]
        ATTR_SERVICE_NAME: "chase-light-backend"
    Tracing: Active

    Tags:
      service: !Sub "chase-light-app"
      env: !Ref Stage
Parameters:
  UseAws:
    Type: String
    Default: 'true'
    Description: Flag to indicate if running in AWS environment
  Stage:
    Type: String
    Default: 'dev'
    Description: Stage environment (dev, staging, prod)
  FrontendUrl:
    Type: String
    Default: '*'
    Description: Allowed origins list for HttpApi CORS (use * or comma-separated origins)
  OtlpLayerVersion:
    Type: String
    Description: OTLPレイヤのバージョン番号

Conditions:
  UseParamsSecretsExtension: !Equals [!Ref UseAws, "true"]
  IsProd: !Equals [!Ref Stage, "prod"]

Resources:
  BackendHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: $default
      CorsConfiguration:
        AllowOrigins: ["*"]
        AllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "traceparent"
          - "tracestate"
          - "baggage"
          - "X-Amzn-Trace-Id"
        AllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
        AllowCredentials: false
      AccessLogSettings:
        DestinationArn: !GetAtt BackendHttpApiAccessLogGroup.Arn
        Format: '{"requestId":"$context.requestId","stage":"$context.stage","httpMethod":"$context.httpMethod","path":"$context.path","status":"$context.status","ip":"$context.identity.sourceIp","userAgent":"$context.identity.userAgent","integrationError":"$context.integrationErrorMessage","routeKey":"$context.routeKey"}'

  BackendHttpApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${Stage}-chase-light-backend-http-api-access"
      RetentionInDays: 14

  # SQS Queues
  ProcessUpdatesQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-chase-light-process-updates-queue"
      VisibilityTimeout: 360
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt ProcessUpdatesDeadLetterQueue.Arn
        maxReceiveCount: 3

  ProcessUpdatesDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-chase-light-process-updates-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  # Translation Jobs Queue
  TranslationJobsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-chase-light-translation-jobs-queue"
      VisibilityTimeout: 360
      MessageRetentionPeriod: 1209600  # 14 days
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TranslationJobsDeadLetterQueue.Arn
        maxReceiveCount: 3

  TranslationJobsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "${Stage}-chase-light-translation-jobs-dlq"
      MessageRetentionPeriod: 1209600  # 14 days

  SharedLambdaPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${Stage}-chase-light-shared-lambda"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${Stage}-chase-light-*"
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/supabase/db_url"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/auth0/domain"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/auth0/audience"
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/auth0/app_audience"
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
            Resource: '*'

  # Lambda Functions
  ListDetectTargetsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-list-detect-targets"
      CodeUri: ../dist/lambda/list-detect-targets/
      Handler: index.handler
      Description: 'List detect targets for monitoring'
      Policies:
        - !Ref SharedLambdaPolicy

  DetectDataSourceUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-detect-datasource-updates"
      CodeUri: ../dist/lambda/detect-datasource-updates/
      Handler: index.handler
      Description: 'Detect updates for a data source'
      Policies:
        - !Ref SharedLambdaPolicy

  ProcessUpdatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-process-updates"
      CodeUri: ../dist/lambda/process-updates/
      Handler: index.handler
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessUpdatesQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - !Ref SharedLambdaPolicy
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/openai/api_key"
        - Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt ProcessUpdatesQueue.Arn

  TranslateActivityBodyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-translate-activity-body"
      CodeUri: ../dist/lambda/translate-activity-body/
      Handler: index.handler
      Runtime: nodejs22.x
      Timeout: 300
      MemorySize: 512
      ReservedConcurrentExecutions: 5
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TranslationJobsQueue.Arn
            BatchSize: 1
            MaximumBatchingWindowInSeconds: 0
      Policies:
        - !Ref SharedLambdaPolicy
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/openai/api_key"
        - Statement:
          - Effect: Allow
            Action:
              - sqs:ReceiveMessage
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
            Resource: !GetAtt TranslationJobsQueue.Arn

  GenerateDigestNotificationsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-generate-digest-notifications"
      CodeUri: ../dist/lambda/generate-digest-notifications/
      Handler: index.handler
      Description: 'Generate digest notifications for subscribed users'
      Timeout: 120
      Environment:
        Variables:
          DIGEST_DEFAULT_LIMIT: "200"
      Events:
        GenerateDigestNotificationsSchedule:
          Type: Schedule
          Properties:
            Name: !Sub "${Stage}-chase-light-generate-digest-notifications-schedule"
            Description: "Run digest notification generation every 30 minutes"
            Schedule: "cron(0/30 * * * ? *)"
      Policies:
        - !Ref SharedLambdaPolicy
        - Statement:
          - Effect: Allow
            Action:
              - ssm:GetParameter
            Resource:
              - !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${Stage}-chase-light/openai/api_key"

  BackendApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Stage}-chase-light-backend-api"
      CodeUri: ../dist/lambda/api/
      Handler: index.handler
      Description: 'Hono API handler behind HttpApi'
      MemorySize: 512
      Timeout: 120
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref BackendHttpApi
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref BackendHttpApi
            Path: /{proxy+}
            Method: ANY
      Policies:
        - !Ref SharedLambdaPolicy

  # Step Functions State Machine
  DataSourceUpdateDetectionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: !Sub "${Stage}-chase-light-data-source-update-detection"
      DefinitionUri: data-source-update-detection.asl.json
      DefinitionSubstitutions:
        ListDetectTargetsFunctionArn: !GetAtt ListDetectTargetsFunction.Arn
        DetectDataSourceUpdatesFunctionArn: !GetAtt DetectDataSourceUpdatesFunction.Arn
        ProcessUpdatesFunction: !GetAtt ProcessUpdatesFunction.Arn
        ProcessUpdatesQueueUrl: !Ref ProcessUpdatesQueue
        DataSourceUpdateDetectionLogGroup.Arn: !GetAtt DataSourceUpdateDetectionLogGroup.Arn
      Logging:
        Level: ALL
        IncludeExecutionData: true
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt DataSourceUpdateDetectionLogGroup.Arn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource:
                - !GetAtt ListDetectTargetsFunction.Arn
                - !GetAtt DetectDataSourceUpdatesFunction.Arn
                - !GetAtt ProcessUpdatesFunction.Arn
        - Statement:
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: !GetAtt ProcessUpdatesQueue.Arn
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogDelivery
                - logs:GetLogDelivery
                - logs:UpdateLogDelivery
                - logs:DeleteLogDelivery
                - logs:ListLogDeliveries
                - logs:PutResourcePolicy
                - logs:DescribeResourcePolicies
                - logs:DescribeLogGroups
              Resource: "*"
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:DescribeLogStreams
              Resource:
                - !GetAtt DataSourceUpdateDetectionLogGroup.Arn
                - !Sub "${DataSourceUpdateDetectionLogGroup.Arn}:*"

  # CloudWatch Log Group for Step Functions
  DataSourceUpdateDetectionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/stepfunctions/${Stage}-chase-light-data-source-update-detection"
      RetentionInDays: 30

  # EventBridge Rule for daily execution
  DataSourceUpdateDetectionScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${Stage}-chase-light-data-source-update-detection-schedule"
      Description: "Daily execution of data source update detection workflow"
      ScheduleExpression: "cron(0 8 * * ? *)"  # Daily at 17:00 JST (08:00 UTC)
      State: ENABLED
      Targets:
        - Arn: !Ref DataSourceUpdateDetectionStateMachine
          Id: "DataSourceUpdateDetectionTarget"
          RoleArn: !GetAtt EventBridgeExecutionRole.Arn

  # IAM Role for EventBridge to execute Step Functions
  EventBridgeExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: StepFunctionsExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - states:StartExecution
                Resource: !Ref DataSourceUpdateDetectionStateMachine

  # SNS Topic for alerts
  AlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Stage}-chase-light-alerts"
      DisplayName: "Data source update detection alerts"

  # CloudWatch Alarms
  StepFunctionsExecutionFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-chase-light-stepfunctions-execution-failed"
      AlarmDescription: "Alert when Step Functions execution fails"
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: DataSourceUpdateDetectionStateMachineArn
          Value: !Ref DataSourceUpdateDetectionStateMachine
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-chase-light-lambda-errors"
      AlarmDescription: "Alert when Lambda functions have errors"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProcessUpdatesFunction
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  ProcessUpdatesDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-chase-light-dlq-messages"
      AlarmDescription: "Alert when messages appear in DLQ"
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ProcessUpdatesDeadLetterQueue.QueueName
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

  TranslationJobsDeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Stage}-chase-light-translation-dlq-messages"
      AlarmDescription: "Alert when messages appear in Translation Jobs DLQ"
      MetricName: ApproximateNumberOfVisibleMessages
      Namespace: AWS/SQS
      Statistic: Maximum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt TranslationJobsDeadLetterQueue.QueueName
      AlarmActions:
        - !Ref AlertsTopic
      TreatMissingData: notBreaching

Outputs:
  BackendApiEndpoint:
    Description: 'Base URL of the Backend HttpApi stage'
    Value: !Sub "${BackendHttpApi.ApiEndpoint}/${Stage}"
    Export:
      Name: !Sub "${Stage}-chase-light-BackendApiEndpoint"

  DataSourceUpdateDetectionStateMachineArn:
    Description: 'ARN of the data source update detection state machine'
    Value: !Ref DataSourceUpdateDetectionStateMachine
    Export:
      Name: !Sub "${Stage}-chase-light-DataSourceUpdateDetectionStateMachineArn"

  ListDetectTargetsFunctionArn:
    Description: 'ARN of the list detect targets function'
    Value: !GetAtt ListDetectTargetsFunction.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-ListDetectTargetsFunctionArn"

  DetectDataSourceUpdatesFunctionArn:
    Description: 'ARN of the detect data source updates function'
    Value: !GetAtt DetectDataSourceUpdatesFunction.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-DetectDataSourceUpdatesFunctionArn"

  ProcessUpdatesFunctionArn:
    Description: 'ARN of the process updates function'
    Value: !GetAtt ProcessUpdatesFunction.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-ProcessUpdatesFunctionArn"

  ProcessUpdatesQueueUrl:
    Description: 'URL of the process updates SQS queue'
    Value: !Ref ProcessUpdatesQueue
    Export:
      Name: !Sub "${Stage}-chase-light-ProcessUpdatesQueueUrl"

  ProcessUpdatesQueueArn:
    Description: 'ARN of the process updates SQS queue'
    Value: !GetAtt ProcessUpdatesQueue.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-ProcessUpdatesQueueArn"

  ScheduleRuleArn:
    Description: 'ARN of the EventBridge schedule rule'
    Value: !GetAtt DataSourceUpdateDetectionScheduleRule.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-ScheduleRuleArn"

  AlertsTopicArn:
    Description: 'ARN of the SNS alerts topic'
    Value: !Ref AlertsTopic
    Export:
      Name: !Sub "${Stage}-chase-light-AlertsTopicArn"

  TranslateActivityBodyFunctionArn:
    Description: 'ARN of the translate activity body function'
    Value: !GetAtt TranslateActivityBodyFunction.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-TranslateActivityBodyFunctionArn"

  TranslationJobsQueueUrl:
    Description: 'URL of the translation jobs SQS queue'
    Value: !Ref TranslationJobsQueue
    Export:
      Name: !Sub "${Stage}-chase-light-TranslationJobsQueueUrl"

  TranslationJobsQueueArn:
    Description: 'ARN of the translation jobs SQS queue'
    Value: !GetAtt TranslationJobsQueue.Arn
    Export:
      Name: !Sub "${Stage}-chase-light-TranslationJobsQueueArn"
