name: Setup Playwright Environment
description: Setup Playwright environment with CJK fonts and browser dependencies

runs:
  using: composite
  steps:
    - name: Install CJK fonts
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends fonts-noto-cjk fonts-noto-color-emoji
        sudo fc-cache -f

    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      with:
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: "24"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Cache Playwright browsers
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('packages/frontend/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Install Playwright browsers
      shell: bash
      run: pnpm --filter frontend test:e2e:install