export const SUMMARIZATION_DEFAULT_MODEL = "gpt-4o-mini"
export const SUMMARIZATION_DEFAULT_MAX_TOKENS = 1200
export const SUMMARIZATION_DEFAULT_TEMPERATURE = 0.2

export const EXTERNAL_AI_API_USE_STUB_ENV = "USE_EXTERNAL_AI_API_STUB"
