AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template for Nuxt 3 SSR frontend deployed to AWS Lambda behind an HTTP API.
  Build with NITRO_PRESET=aws-lambda pnpm --filter frontend build before sam build.

Parameters:
  ProjectName:
    Type: String
    Default: chase-light-frontend
    Description: Base name used for resource naming.
  UseAws:
    Type: String
    Default: 'true'
    Description: Flag to indicate if running in AWS environment
  Stage:
    Type: String
    AllowedValues:
      - dev
      - prod
    Default: dev
    Description: Deployment stage used in names and API stage.
  SecretId:
    Type: String
    Description: Secrets Manager secret name (recommended) containing JSON with Nuxt runtime values. Used with resolve:secretsmanager and IAM policy.
  AssetBucketName:
    Type: String
    Default: dev-chase-light-frontend-assets
    Description: S3 bucket name to host .output/public (e.g., dev-chase-light-frontend-assets / prod-chase-light-frontend-assets).
  MemorySize:
    Type: Number
    Default: 1024
    MinValue: 128
    MaxValue: 10240
    Description: Lambda memory size (MB).
  Timeout:
    Type: Number
    Default: 15
    MinValue: 3
    MaxValue: 29
    Description: Lambda timeout (seconds).
  LogRetentionDays:
    Type: Number
    Default: 14
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365]
    Description: CloudWatch Logs retention in days.

Conditions:
  UseParamsSecretsExtension: !Equals [!Ref UseAws, 'true']

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    Layers: !If
      - UseParamsSecretsExtension
      - - arn:aws:lambda:ap-northeast-1:133490724326:layer:AWS-Parameters-and-Secrets-Lambda-Extension:21
      - !Ref AWS::NoValue
    MemorySize: !Ref MemorySize
    Timeout: !Ref Timeout
    Tracing: Active
    Environment:
      Variables:
        NODE_ENV: production

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref AssetBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 30

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !GetAtt AssetsBucket.Arn
              - !Join ['', [!GetAtt AssetsBucket.Arn, '/*']]
            Condition:
              Bool:
                aws:SecureTransport: false

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: !Sub '${Stage}-${ProjectName}'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - PATCH
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
          - X-Trace-Id
        MaxAge: 600
        AllowCredentials: false

  NuxtFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ReadNuxtRuntimeSecret
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${SecretId}*'

  NuxtFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${Stage}-${ProjectName}'
      Description: Nuxt 3 SSR Lambda handler built with NITRO_PRESET=aws-lambda
      CodeUri: ../.output/server
      Handler: index.handler
      Role: !GetAtt NuxtFunctionRole.Arn
      Environment:
        Variables:
          USE_AWS: !Ref UseAws
          APP_STAGE: !Ref Stage
          # NOTE: Do not reference HttpApi here to avoid circular dependencies (HttpApi <-> NuxtFunction).
          # Set this value in Secrets Manager (SecretString:NUXT_PUBLIC_BASE_URL) instead.
          SECRET_ID: !Ref SecretId
      LoggingConfig:
        LogFormat: JSON
        ApplicationLogLevel: INFO
        SystemLogLevel: INFO
      Tags:
        Project: !Ref ProjectName
        Stage: !Ref Stage
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: ANY
        ApiProxy:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY

  NuxtFunctionInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt NuxtFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/*/*/*'

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      # Avoid referencing NuxtFunction (resource) to prevent circular dependencies.
      LogGroupName: !Sub '/aws/lambda/${Stage}-${ProjectName}'
      RetentionInDays: !Ref LogRetentionDays

Outputs:
  ApiEndpoint:
    Description: HTTP API endpoint for the Nuxt app.
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}'
  LambdaFunctionName:
    Description: Deployed Lambda function name.
    Value: !Ref NuxtFunction
  AssetsBucketName:
    Description: Bucket for static assets (.output/public).
    Value: !Ref AssetsBucket
