name: API CI

on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
  pull_request:
    paths:
      - 'packages/api/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo

    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:15.6-bookworm
        ports:
          - '10000:5432'
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.9.0'

      - uses: actions/cache/restore@v4
        id: pnpm-cache
        with:
          path: |
            ~/.local/share/pnpm
            node_modules
            packages/api/node_modules
          key: api-ci-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            api-ci-pnpm-

      - name: Install dependencies
        run: |
          cd packages/api
          pnpm install --frozen-lockfile

      - name: Run tests
        run: |
          cd packages/api
          npx prisma generate
          pnpm test

      - uses: actions/cache/save@v4
        if: github.ref_name == 'main'
        with:
          path: |
            ~/.local/share/pnpm
            node_modules
            packages/api/node_modules
          key: ${{ steps.pnpm-cache.outputs.cache-primary-key }}
