name: Deploy(APP)
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - dev
          - prod

concurrency: ${{ github.workflow }}

jobs:
  api-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment: ${{ github.event.inputs.environment }}
    env:
      ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ID }}:role/${{ secrets.ROLE_NAME }}
      SESSION_NAME: gh-oidc-${{ vars.PROJECT_NAME }}-${{ github.run_id }}-${{ github.run_attempt }}
      STAGE: ${{ github.event.inputs.environment }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT: ${{ secrets.AWS_ID }}
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          role-session-name: ${{ env.SESSION_NAME }}
          aws-region: ${{ vars.AWS_REGION }}

      - uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.9

      - name: install js package
        run: |
          cd packages/app
          pnpm install --frozen-lockfile

      - name: deploy
        run: |
          cd packages/app
          pnpm build
          npx serverless deploy --stage ${{ env.STAGE }} --verbose
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          NUXT_SESSION_PASSWORD: ${{ secrets.NUXT_SESSION_PASSWORD }}
          NUXT_API_HOST: ${{ secrets.API_URL }}
          NUXT_OAUTH_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          NUXT_OAUTH_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          NUXT_OAUTH_AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          NUXT_OAUTH_AUTH0_REDIRECT_URL: ""
          NUXT_OAUTH_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          NUXT_PUBLIC_API_HOST: ""
          NUXT_PUBLIC_OAUTH_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          NUXT_PUBLIC_OAUTH_AUTH0_CLIENT_ID: ""
          NUXT_PUBLIC_OAUTH_AUTH0_REDIRECT_URL: ""
          NUXT_PUBLIC_OAUTH_AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
          AWS_ACCOUNT: ${{ secrets.AWS_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
