name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint

      - name: Type check
        run: pnpm run lint:type

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build

  e2e:
    runs-on: ubuntu-latest
    needs: test

    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:15-bookworm
        env:
          POSTGRES_DB: chase_light
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_HOST_AUTH_METHOD: md5
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Initialize database
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
          PGPASSWORD=password psql -h localhost -U postgres -d chase_light -f database/init/01-create-sessions-table.sql

      - name: Install Playwright browsers
        run: pnpm --filter frontend test:e2e:install

      - name: Build frontend
        run: pnpm --filter frontend build

      - name: Start frontend
        run: pnpm --filter frontend preview &
        env:
          AUTH0_SECRET: test-secret
          AUTH0_BASE_URL: http://localhost:3000
          AUTH0_ISSUER_BASE_URL: ""
          AUTH0_CLIENT_ID: ""
          AUTH0_CLIENT_SECRET: ""
          DATABASE_URL: postgresql://postgres:password@localhost:5432/chase_light

      - name: Wait for frontend to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 1; done'

      - name: Run E2E tests
        run: pnpm --filter frontend test:e2e
        env:
          AUTH0_SECRET: test-secret
          AUTH0_BASE_URL: http://localhost:3000
          AUTH0_ISSUER_BASE_URL: ""
          AUTH0_CLIENT_ID: ""
          AUTH0_CLIENT_SECRET: ""
          DATABASE_URL: postgresql://postgres:password@localhost:5432/chase_light

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/frontend/playwright-report/
          retention-days: 30