name: Tests

on:
  push:
    branches: [main, develop]
    paths:
      - "pnpm-lock.yaml"
      - "packages/frontend/**"
      - "packages/backend/**"
      - "!packages/frontend/docs/**"
      - "!packages/backend/docs/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "pnpm-lock.yaml"
      - "packages/frontend/**"
      - "packages/backend/**"
      - "!packages/frontend/docs/**"
      - "!packages/backend/docs/**"

jobs:
  # 変更されたファイルを検出
  detect-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      frontend-changed: ${{ steps.changes.outputs.frontend }}
      backend-changed: ${{ steps.changes.outputs.backend }}
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 5.0.0
        with:
          fetch-depth: 0

      - name: Detect changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            frontend:
              - 'packages/frontend/**'
              - 'pnpm-lock.yaml'
            backend:
              - 'packages/backend/**'
              - 'pnpm-lock.yaml'

  # Frontend テスト（フロントエンド変更時のみ）
  test-frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Frontend Test
        run: pnpm --filter frontend test

      - name: Frontend Build
        run: pnpm --filter frontend build

  # Backend テスト（バックエンド変更時のみ）
  test-backend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: detect-changes
    if: needs.detect-changes.outputs.backend-changed == 'true'
    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:15-bookworm
        env:
          POSTGRES_DB: chase_light_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "password"
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d chase_light_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Backend test
        run: pnpm --filter backend test:coverage

      - name: Upload backend coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
        with:
          files: packages/backend/coverage/lcov.info
          flags: backend
          name: backend-coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Backend Build
        run: pnpm --filter backend build

  # E2E テスト（どちらかのテストが成功した場合）
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: [detect-changes, test-frontend, test-backend]
    if: |
      always() &&
      (
        (needs.detect-changes.outputs.frontend-changed == 'true' && needs.test-frontend.result == 'success') ||
        (needs.detect-changes.outputs.backend-changed == 'true' && needs.test-backend.result == 'success') ||
        (needs.detect-changes.outputs.frontend-changed != 'true' && needs.detect-changes.outputs.backend-changed != 'true')
      )

    services:
      postgres:
        image: public.ecr.aws/docker/library/postgres:15-bookworm
        env:
          POSTGRES_DB: chase_light_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "password"
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres -d chase_light_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4

      - name: Setup Playwright Environment
        uses: ./.github/actions/setup-playwright-environment

      - name: Initialize database
        run: |
          pnpm --filter backend test:migrate

      - name: Build frontend
        run: |
          rm -rf packages/frontend/.output
          pnpm --filter frontend build

      - name: Start frontend
        run: pnpm --filter frontend preview > nuxt_preview.log 2>&1 &
        env:
          AUTH0_SECRET: dummy
          AUTH0_BASE_URL: http://localhost:3000
          AUTH0_ISSUER_BASE_URL: ""
          AUTH0_CLIENT_ID: "clientid"
          AUTH0_CLIENT_SECRET: "dummy"
          NUXT_SESSION_SECRET: "dummy"
          DATABASE_URL: postgresql://postgres:password@localhost:5432/chase_light_test?sslmode=disable
          NUXT_PUBLIC_BASE_URL: http://localhost:3000
          APP_STAGE: dev

      - name: Wait for frontend to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:3000; do sleep 1; done'

      - name: VRT Tests
        run: pnpm --filter frontend test:vrt
        env:
          # CI環境でのVRTテスト実行
          CI: true

      - name: Upload VRT test results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: vrt-test-results
          path: packages/frontend/test-results/
          retention-days: 30

      - name: Upload VRT Playwright report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: vrt-playwright-report
          path: packages/frontend/playwright-report-storybook/
          retention-days: 30

      - name: Run E2E tests
        run: pnpm --filter frontend test:e2e
        env:
          AUTH0_SECRET: dummy
          AUTH0_BASE_URL: http://localhost:3000
          AUTH0_ISSUER_BASE_URL: ""
          AUTH0_CLIENT_ID: "dummy"
          AUTH0_CLIENT_SECRET: "dummy"
          NUXT_SESSION_SECRET: "dummy"
          DATABASE_URL: postgresql://postgres:password@localhost:5432/chase_light_test?sslmode=disable
          NUXT_PUBLIC_BASE_URL: http://localhost:3000
          APP_STAGE: dev

      - name: Upload Playwright report
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: playwright-report
          path: packages/frontend/playwright-report/
          retention-days: 30

      - name: Upload Nuxt preview log
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: always()
        with:
          name: nuxt-preview-log
          path: nuxt_preview.log
          retention-days: 30
