name: Test Backend

on:
  push:
    branches: [main, develop]
    paths:
      - 'pnpm-lock.yaml'
      - 'packages/backend/**'
      - '!packages/backend/docs/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'pnpm-lock.yaml'
      - 'packages/backend/**'
      - '!packages/backend/docs/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Backend test
        run: pnpm --filter backend test

      - name: Backend Build
        run: pnpm --filter backend build

