#!/usr/bin/env tsx

import { build } from 'esbuild'
import { writeFileSync, mkdirSync, readFileSync } from 'fs'
import { resolve, dirname } from 'path'
import { execSync } from 'child_process'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const projectRoot = resolve(__dirname, '../..')
const buildDir = resolve(projectRoot, 'build')
const userHandlerEntry = resolve(
  projectRoot,
  'src/handlers/api-gateway/user/index.ts',
)

// npm installするパッケージ（serverless.tsのexternalから@opentelemetry/*とopenaiを除外）
const externalPackages = ['aws-lambda', '@prisma/client', 'zod']

async function buildUserHandler() {
  console.log('Building user handler...')

  // buildディレクトリを作成
  mkdirSync(buildDir, { recursive: true })

  // ESBuildでビルド
  await build({
    entryPoints: [userHandlerEntry],
    bundle: true,
    platform: 'node',
    target: 'node18',
    format: 'esm',
    outdir: buildDir,
    external: externalPackages,
    minify: false,
    sourcemap: true,
    splitting: false,
    metafile: true,
  })

  // package.jsonを作成
  const packageJson = {
    name: 'chase-light-api',
    version: '1.0.0',
    type: 'module',
    devDependencies: {
      prisma: 'latest',
    },
    dependencies: Object.fromEntries(
      externalPackages.map((pkg) => [pkg, 'latest']),
    ),
  }

  writeFileSync(
    resolve(buildDir, 'package.json'),
    JSON.stringify(packageJson, null, 2),
  )

  // prisma/schema.prismaをbuildディレクトリにコピー
  console.log('Copying Prisma schema...')
  const prismaSchemaPath = resolve(projectRoot, 'prisma/schema.prisma')
  const buildPrismaSchemaPath = resolve(buildDir, 'schema.prisma')
  writeFileSync(
    buildPrismaSchemaPath,
    `// This file is generated by the build script. Do not edit directly.\n\n${readFileSync(prismaSchemaPath, 'utf8')}`,
  )

  console.log('Installing dependencies...')
  // buildディレクトリでnpm install実行
  execSync('npm install', {
    cwd: buildDir,
    stdio: 'inherit',
  })

  execSync('npx prisma generate', {
    cwd: buildDir,
    stdio: 'inherit',
  })

  // prismaをアンインストール
  console.log('Uninstalling Prisma from build directory...')
  execSync('npm uninstall prisma', {
    cwd: buildDir,
    stdio: 'inherit',
  })

  // node_modules/aws-sdkフォルダを削除
  console.log('Cleaning up aws-sdk module...')
  const awsSdkPath = resolve(buildDir, 'node_modules/aws-sdk')
  if (awsSdkPath) {
    execSync(`rm -rf ${awsSdkPath}`, {
      cwd: buildDir,
      stdio: 'inherit',
    })
  }

  // 以下にマッチするファイルを削除
  // - build/node_modules/.prisma/client/*-engine-debian-*
  // - build/node_modules/@prisma/engines/*-engine-debian-*
  console.log('Cleaning up Prisma engines...')
  const prismaClientPath = resolve(buildDir, 'node_modules/.prisma/client')
  const prismaEnginesPath = resolve(buildDir, 'node_modules/@prisma/engines')
  execSync(`rm -rf ${prismaClientPath}/*-engine-debian-*`, {
    cwd: buildDir,
    stdio: 'inherit',
  })
  execSync(`rm -rf ${prismaEnginesPath}/*-engine-debian-*`, {
    cwd: buildDir,
    stdio: 'inherit',
  })

  console.log('Build completed successfully!')
}

buildUserHandler().catch(console.error)
